### ISSUE TITLE
Sort problem

### ISSUE THREAD

**Issue by honis56** [AnKing-Memberships/advanced-browser#163]
Sort by due (clicking on the headline "Due" does not work correctly.

Look at the last 3 lines of

![error](https://user-images.githubusercontent.com/60839774/213818962-196cd770-b80e-4fef-b197-ef4b761f2189.png)

**Comment by ijgnd** [comment]
This is most likely not related to the Advanced Browser add-on.

Check the manual, https://docs.ankiweb.net/browsing.html#columns :

> The due date for cards in review or (re)learning, and the position in the new card queue for new cards. The line is wrapped in brackets if the card is suspended or buried. Sorting is done **by type and only then by date** or position.

I guess that the cards at the bottom are not regular review cards, but e.g. that you recently failed that still have a relearning step.

&nbsp;

&nbsp;

If you checked all the card info (and how you rated the card the last time you reviewed it by clicking the "info" entry from the context menu and still think there's a bug in the advanced browser add-on: More info is needed, otherwise this will be ignored.

Please close Anki, then start it again while holding down the shift key, which will disable any add-ons you have installed. Then from the main window go to Tools->Check Database. Then go to the browser and check the browser again: Is the sorting now correct or is it still broken? 

If it's still broken then the problem is not with the add-on Advanced Browser but with Anki itself. In this case report your problem to forums.ankiweb.net.

&nbsp;

If it doesn't happen without any add-ons rule out add-on interference: 

> If the problem goes away when add-ons are disabled, you can narrow down the culprit by disabling one or more add-ons, restarting Anki, and seeing if the problem goes away. If you have lots of them, you can select the top half of your add-ons in the Add-ons screen and disable them. If after restarting Anki, the problem is still there, try the other half instead. Once you’ve found the half that is causing the problem, divide that half into half again, and repeat. You should be able to narrow it down in around ~6 steps that way. 

Tell us if this only happens with the advanced browser. Which anki version do you use, what OS do you use? If it's not 2.1.55 try the Advanced Browser with the latest version.

**Comment by honis56** [comment]
Thank you for your polite reply.

Everything is fine, you are right, it is my fault. I have not read carefully. I apologise for bothering you. 

Best regards
